MergePing/NamHoJung

- src/main/java/com/ohgiraffers/mergyping/comment/model/dto/user/controller/UserController.java
- src/main/java/com/ohgiraffers/mergyping/comment/model/dto/user/model/dto/LoginUserDTO.java
- src/main/java/com/ohgiraffers/mergyping/comment/model/dto/user/model/dto/SignupDTO.java
- src/main/java/com/ohgiraffers/mergyping/comment/model/dto/user/model/service/UserService.java
- src/main/resources/static/css/reset.css
- src/main/resources/templates/main/main.html
메인페이지 프론트 구현 완료
<br/>
#1
<br/>
<br/>
<br/>
> [FEATURE][MainPage] 메인페이지 구현

- src/main/java/com/ohgiraffers/mergyping/user/controller/MainController.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dao/MainMapper.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dto/MainDTO.java
- src/main/java/com/ohgiraffers/mergyping/user/model/service/MainService.java
- src/main/resources/mappers/MainMapper.xml
- src/main/resources/static/css/mainpage/mainpage-darkmode.css
- src/main/resources/templates/main/main.html
메인페이지 베스트 정원 무서워요 상위 4개 디비 연결
<br/>
#44
<br/>
<br/>
<br/>
> [FEATURE][ConnectDBMain]메인페이지 베스트 게시물 DB 연결

- src/main/java/com/ohgiraffers/mergyping/user/controller/UserController.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dao/UserMapper.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dto/UserDTO.java
- src/main/java/com/ohgiraffers/mergyping/user/model/service/UserService.java
- src/main/resources/mappers/UserMapper.xml
- src/main/resources/static/css/admin/adminmanagement.css
- src/main/resources/templates/user/admin/adminmanagement.html
이제 유저 조회에서 닉네임을 통해 검색할수 있고, 상세 조회에서 탈퇴처리, 닉네임 수정하기를 할 수 있습니다.
<br/>
#32 
<br/>
<br/>
<br/>
> [FEATURE][ADMIN-USER-DETAIL]유저 검색, 유저 탈퇴 처리, 유저 닉네임 수정하기

- src/main/java/com/ohgiraffers/mergyping/config/SecurityConfig.java
- src/main/java/com/ohgiraffers/mergyping/post/controller/PostController.java
- src/main/java/com/ohgiraffers/mergyping/post/model/dao/PostMapper.java
- src/main/java/com/ohgiraffers/mergyping/post/model/dto/PostDTO.java
- src/main/java/com/ohgiraffers/mergyping/post/model/dto/SelectPostDTO.java
- src/main/java/com/ohgiraffers/mergyping/post/model/service/PostService.java
- src/main/resources/mappers/PostMapper.xml
- src/main/resources/static/css/post/post.css
- src/main/resources/templates/main/main.html
- src/main/resources/templates/post/post.html
- src/main/resources/templates/post/selectpost.html
게시글 제목을 클릭하면 상세페이지로 들어가집니다
아직 자스랑 프론트는 완성이 안되어 있어요
<br/>
#40
<br/>
<br/>
<br/>
> [FEATURE][SELECT_POST]게시물 상세조회 및 디비 연결

- src/main/java/com/ohgiraffers/mergyping/auth/controller/AuthController.java
- src/main/java/com/ohgiraffers/mergyping/auth/model/AuthDetails.java
- src/main/java/com/ohgiraffers/mergyping/auth/model/service/AuthService.java
- src/main/java/com/ohgiraffers/mergyping/config/SecurityConfig.java
- src/main/java/com/ohgiraffers/mergyping/user/controller/MainController.java
- src/main/java/com/ohgiraffers/mergyping/user/controller/MyPageController.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dao/MyPageMapper.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dto/LoginUserDTO.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dto/MyPageDTO.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dto/MyPagePostDTO.java
- src/main/java/com/ohgiraffers/mergyping/user/model/service/MyPageService.java
- src/main/resources/mappers/MyPageMapper.xml
- src/main/resources/mappers/SignupMapper.xml
- src/main/resources/templates/main/main.html
- src/main/resources/templates/user/mypage/userinfo.html
로그인하고 로그인한 유저 닉네임 불러오고 이메일 불러오고 게시글 불러오기 만약 닉네임 수정했을때 바뀌는것도 구현
<br/>
#62 
<br/>
<br/>
<br/>
> [FEATURE][MypageLoginNickname]마이페이지 로그인 닉네임 연동

- src/main/java/com/ohgiraffers/mergyping/post/controller/PostController.java
- src/main/java/com/ohgiraffers/mergyping/post/model/dao/PostMapper.java
- src/main/java/com/ohgiraffers/mergyping/post/model/dto/SelectPostDTO.java
- src/main/java/com/ohgiraffers/mergyping/post/model/service/PostService.java
- src/main/resources/mappers/PostMapper.xml
- src/main/resources/static/css/post/post.css
- src/main/resources/static/css/post/selectpost.css
- src/main/resources/templates/post/selectpost.html
이미지 클릭시 블러처리 풀림, 게시글 내에서도 즐겨찾기 가능, 게시글의 길이에 따라 하단 정보창의 위치가 바뀜
<br/>
#75
<br/>
<br/>
<br/>
> [FEATURE][PostDB/ImgBlur]게시글 상세조회 조정 및 이미지 블러처리

- src/main/java/com/ohgiraffers/mergyping/user/controller/MainController.java
- src/main/java/com/ohgiraffers/mergyping/user/controller/MyPageController.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dao/MyPageMapper.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dto/MyPageDTO.java
- src/main/java/com/ohgiraffers/mergyping/user/model/service/MyPageService.java
- src/main/resources/mappers/MyPageMapper.xml
- src/main/resources/static/css/mypage/mypageinfo.css
- src/main/resources/templates/main/main.html
- src/main/resources/templates/user/mypage/userinfo.html
개인정보 들어갈때 비밀번호 입력해야하는거 구현했고 비밀번호 변경하는거 구현중입니다.
<br/>
#71 
<br/>
<br/>
비밀번호 변경 만들면서 로그인이 안돼서 스크린샷을 못찍습니다...
<br/>
> [FEATURE][MypagePasswordConfirm]마이페이지->개인정보 들어갈 때 비밀번호 입력 비동기 확인

- src/main/java/com/ohgiraffers/mergyping/config/SecurityConfig.java
- src/main/java/com/ohgiraffers/mergyping/post/controller/PostController.java
- src/main/java/com/ohgiraffers/mergyping/post/model/dao/PostMapper.java
- src/main/java/com/ohgiraffers/mergyping/post/model/dto/FileUploadDTO.java
- src/main/java/com/ohgiraffers/mergyping/post/model/dto/SelectPostDTO.java
- src/main/java/com/ohgiraffers/mergyping/post/model/service/PostService.java
- src/main/resources/mappers/PostMapper.xml
- src/main/resources/templates/post/post.html
- src/main/resources/templates/post/selectpost.html
무서워요 버튼 클릭시 이미지 바뀌면서 기존 무서워요 수에 1이 더해짐
다시누르면 취소가 되고 -1이 됨
디비에 연결까지 완료
<br/>
#69
<br/>
<br/>
<br/>
> [FEATURE][ScaryBtnDBConnect] 무서워요 안무서워요 비동기 db연결

- src/main/java/com/ohgiraffers/mergyping/user/controller/AdminNoticeController.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dao/AdminNoticeDetailMapper.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dto/AdminNoticeDetailDTO.java
- src/main/java/com/ohgiraffers/mergyping/user/model/service/AdminNoticeService.java
- src/main/resources/static/css/admin/adminnotice.css
- src/main/resources/static/css/admin/adminnoticedetail.css
- src/main/resources/templates/user/admin/adminmanagement.html
- src/main/resources/templates/user/admin/adminnotice.html
- src/main/resources/templates/user/admin/adminnoticedetail.html
관리자 공지사항 상세보기
<br/>
#64 
<br/>
<br/>
<br/>
> [FEATURE][NoticeSelectDetail]관리자 공지사항 상세보기

- src/main/java/com/ohgiraffers/mergyping/user/controller/AdminNoticeController.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dao/AdminNoticeMapper.java
- src/main/java/com/ohgiraffers/mergyping/user/model/service/AdminNoticeService.java
- src/main/resources/mappers/AdminNoticeMapper.xml
- src/main/resources/static/css/admin/adminnoticedetail.css
- src/main/resources/templates/user/admin/adminnoticedetail.html
관리자 공지사항 삭제할 수 있습니다.
<br/>
<br/>
<br/>
<br/>
> [FEATURE}[AdminDeleteNotice]관리자 공지사항 삭제

- src/main/java/com/ohgiraffers/mergyping/user/controller/MyPageController.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dao/MyPageMapper.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dto/MypageCommentDTO.java
- src/main/java/com/ohgiraffers/mergyping/user/model/service/MyPageService.java
- src/main/resources/mappers/MyPageMapper.xml
- src/main/resources/static/css/mypage/mypageactive.css
- src/main/resources/templates/user/mypage/useractive.html
활동기록 로그인한 유저의 작성한 게시글 작성한 댓글 즐겨찾기 조회하기 구현 하였습니다.
<br/>
#90 
<br/>
글이 많아지면 겹쳐서 나오는거 해결 못함 ㅜㅜ
페이징 처리 해결 못함 ㅜㅜ
<br/>
<br/>
> [FEATURE][ActivityRecordWrittenCommentConnectedDB]활동기록 작성 댓글 DB 연동

- src/main/java/com/ohgiraffers/mergyping/user/controller/MainController.java
- src/main/java/com/ohgiraffers/mergyping/user/controller/MyPageController.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dao/MyPageMapper.java
- src/main/java/com/ohgiraffers/mergyping/user/model/service/MyPageService.java
- src/main/resources/mappers/MyPageMapper.xml
- src/main/resources/templates/main/main.html
- src/main/resources/templates/user/mypage/useractive.html
로그인한 유저의 mbti 유형과 mbti 설명 연동 하였습니다!
<br/>
#100 
<br/>
<br/>
<br/>
> [FEATURE][MypageConnectedDB]마이페이지 MBTI DB연동

- src/main/java/com/ohgiraffers/mergyping/user/controller/AdminNoticeController.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dao/AdminNoticeMapper.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dto/AdminNoticeDTO.java
- src/main/java/com/ohgiraffers/mergyping/user/model/service/AdminNoticeService.java
- src/main/resources/mappers/AdminNoticeMapper.xml
- src/main/resources/static/css/admin/adminnotice.css
- src/main/resources/templates/user/admin/adminnotice.html
- src/main/resources/templates/user/admin/adminnoticedetail.html
공지사항 추가 가능
<br/>
#88 
<br/>
<br/>
<br/>
> [FEATURE][INSERTNOTICE] 공지사항 추가

- src/main/java/com/ohgiraffers/mergyping/user/controller/AdminNoticeController.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dao/AdminNoticeMapper.java
- src/main/java/com/ohgiraffers/mergyping/user/model/service/AdminNoticeService.java
- src/main/resources/mappers/AdminNoticeMapper.xml
- src/main/resources/static/css/admin/adminnotice.css
- src/main/resources/templates/user/admin/adminnotice.html
공지사항 검색기능입니다.
<br/>
#105 
<br/>
<br/>
<br/>
> [FEAUTRE][SEARCHNOTICE]공지사항 검색

- src/main/java/com/ohgiraffers/mergyping/user/controller/MainController.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dao/MyPageMapper.java
- src/main/java/com/ohgiraffers/mergyping/user/model/service/MyPageService.java
- src/main/resources/mappers/MyPageMapper.xml
- src/main/resources/static/css/mypage/mypage.css
- src/main/resources/templates/main/main.html
마이페이지에서 유저의 등급 조회 구현 등급 마우스 올리면 현재 출석 횟수, 다음 등급, 필요 출석 구현하였습니다!
<br/>
#109 
<br/>
<br/>
<br/>
> [FEATURE][MypageConnectedDB]마이페이지와 등급DB 연결 

- src/main/java/com/ohgiraffers/mergyping/user/controller/MainController.java
- src/main/java/com/ohgiraffers/mergyping/user/controller/MyPageController.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dao/MyPageMapper.java
- src/main/java/com/ohgiraffers/mergyping/user/model/service/MyPageService.java
- src/main/resources/mappers/MyPageMapper.xml
- src/main/resources/static/css/mypage/mypage.css
- src/main/resources/templates/main/main.html
- src/main/resources/templates/user/mypage/userinfo.html
마이페이지에서 회원탈퇴를 하면 일단 바로 삭제 되게 구현 하였습니다!
<br/>
#112 
<br/>
<br/>
<br/>
> [FEATURE][DeleteAccountConnectedDB]회원탈퇴 DB 연결

- src/main/java/com/ohgiraffers/mergyping/user/controller/AdminMainController.java
- src/main/resources/static/css/admin/admin.css
- src/main/resources/static/css/admin/adminnotice.css
- src/main/resources/templates/user/admin/admin.html
- src/main/resources/templates/user/admin/adminmanagement.html
- src/main/resources/templates/user/admin/adminnotice.html
이제 주소창에 admin치면 들어가지고 공지사항 관리랑 회원관리 들어갈수 있습니다 나머지 기능들은 만들면 추가하겠습니다
<br/>
#121 
<br/>
<br/>
<br/>
> [FIX][ADMINPAGECONNECTEDURL]관리자 메인페이지 URL 연결

- src/main/java/com/ohgiraffers/mergyping/user/controller/AdminMainController.java
- src/main/java/com/ohgiraffers/mergyping/user/controller/AdminPostController.java
- src/main/java/com/ohgiraffers/mergyping/user/controller/UserController.java
- src/main/resources/static/css/admin/admin.css
- src/main/resources/static/css/admin/adminnotice.css
- src/main/resources/static/css/admin/adminpost.css
- src/main/resources/templates/user/admin/admin.html
- src/main/resources/templates/user/admin/adminmanagement.html
- src/main/resources/templates/user/admin/adminnotice.html
- src/main/resources/templates/user/admin/adminpost.html
관리자 게시판 관리 프론트입니다.
<br/>
#123 
<br/>
<br/>
<br/>
> [FEATURE][FRONTADMINPOST]관리자 게시판 관리 프론트

- src/main/java/com/ohgiraffers/mergyping/post/controller/PostController.java
- src/main/java/com/ohgiraffers/mergyping/post/model/service/PostService.java
- src/main/resources/mappers/PostMapper.xml
- src/main/resources/static/css/post/post.css
- src/main/resources/templates/post/post.html
게시물 페이징 처리햇습니다
<br/>
#131
<br/>
새로고침할때 가끔 페이징이 풀릴때가 있어요ㅜㅜ
카테고리 페이징은 아직 구현중입니다!
<br/>
<br/>
> [FEATURE][PostPasingProcessing]게시물 페이징 처리

- src/main/java/com/ohgiraffers/mergyping/post/controller/PostController.java
- src/main/java/com/ohgiraffers/mergyping/post/model/dao/PostMapper.java
- src/main/java/com/ohgiraffers/mergyping/post/model/service/PostService.java
- src/main/resources/mappers/PostMapper.xml
- src/main/resources/templates/post/post.html
화살표 이미지 제거 했고 카테고리별로 정렬 가능합니다
<br/>
#131
<br/>
카테고리의 게시물이 5개이면 페이지가 1개만 생겨야하는데 메인의 숫자 3개를 그대로 가져옴(아직 수정더 필요)
<br/>
<br/>
> [FIX][PostPasingProcessing]게시물 페이징 수정

- src/main/java/com/ohgiraffers/mergyping/user/controller/AdminPostController.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dao/AdminPostMapper.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dto/AdminPostDTO.java
- src/main/java/com/ohgiraffers/mergyping/user/model/service/AdminPostService.java
- src/main/resources/mappers/AdminPostMapper.xml
- src/main/resources/static/css/admin/adminpost.css
- src/main/resources/templates/user/admin/adminpost.html
관리자 게시물 전체조회랑 페이지네이션 처리했습니다
<br/>
#128 
<br/>
CSS하다가 다른 기능을 할 시간이 부족해 임시로 배치해놨습니다. 시간이나면 다시 재배치 해보겠습니다.
<br/>
<br/>
> [FEATURE][SELECTADMINPOSTMANAGEMENT]관리자 공지사항 전체조회 & 페이지네이션 처리

- src/main/java/com/ohgiraffers/mergyping/user/controller/AdminPostController.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dao/AdminPostMapper.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dto/AdminPostDTO.java
- src/main/java/com/ohgiraffers/mergyping/user/model/service/AdminPostService.java
- src/main/resources/mappers/AdminPostMapper.xml
- src/main/resources/static/css/admin/adminpost.css
- src/main/resources/static/css/admin/adminpostdetail.css
- src/main/resources/templates/user/admin/adminpost.html
- src/main/resources/templates/user/admin/adminpostdetail.html
관리자 게시물 상세보기입니다. 이미지는 추후 수정예정.
<br/>
#154 
<br/>
<br/>
<br/>
> [FEATURE][ADMINDETAILEDVIEW]관리자 게시물 상세보기

- src/main/java/com/ohgiraffers/mergyping/user/controller/AdminPostController.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dao/AdminPostMapper.java
- src/main/java/com/ohgiraffers/mergyping/user/model/service/AdminPostService.java
- src/main/resources/mappers/AdminPostMapper.xml
- src/main/resources/static/css/admin/adminpostdetail.css
- src/main/resources/templates/user/admin/adminpostdetail.html
이제 관리자가 게시물 상세조회에서 게시물을 삭제 할 수 있습니다.
<br/>
#156 
<br/>
<br/>
<br/>
> [FEATURE][ADMINPAGEDELETEPOSTFUNCTION]관리자 게시물 삭제

- src/main/java/com/ohgiraffers/mergyping/post/model/dto/SelectPostDTO.java
- src/main/java/com/ohgiraffers/mergyping/user/controller/MainController.java
- src/main/java/com/ohgiraffers/mergyping/user/controller/MyPageController.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dao/MyPageMapper.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dto/LoginUserDTO.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dto/MyPageDTO.java
- src/main/java/com/ohgiraffers/mergyping/user/model/service/MyPageService.java
- src/main/resources/mappers/MyPageMapper.xml
- src/main/resources/mappers/PostMapper.xml
- src/main/resources/static/css/mypage/mypageinfo.css
- src/main/resources/templates/main/main.html
- src/main/resources/templates/post/newpost.html
- src/main/resources/templates/user/mypage/useractive.html
- src/main/resources/templates/user/mypage/userinfo.html
마이페이지, 활동기록, 메인에서 사용자 프로필 사진 연동했습니다
<br/>
#148
<br/>
<br/>
<br/>
> [FEATURE][MypageProfileUploadPicture]마이페이지 프로필 사진 연동

- src/main/java/com/ohgiraffers/mergyping/post/controller/PostController.java
- src/main/java/com/ohgiraffers/mergyping/post/model/dao/PostMapper.java
- src/main/java/com/ohgiraffers/mergyping/post/model/dto/InsertPostDTO.java
- src/main/java/com/ohgiraffers/mergyping/post/model/service/PostService.java
- src/main/resources/mappers/PostMapper.xml
- src/main/resources/templates/post/selectpost.html
게시물 유저 이름이 출력되게 변경했고 db에 맞게 나타나도록 연결해놨습니다.
같은 DTO를 쓸경우 insert에서 오류는 안뜨지만 글이 올라가지 않아 DTO를 새로 생성해서 넣어보니 잘 작동됩니다.
그외에 번호에 조인 추가해서 유저 이름이 나타나도록 연결해놨습니다.
<br/>
#165 
<br/>
기존 DTO에 postWriterName을 추가하고 html도 수정 완료
insert할때 유저번호를 입력하는 방식이 아닌 들어가는 방식으로 수정하면 좋을 것 같습니다.
제가 한 부분이 아니기 때문에 혹시 몰라서 이 부분만 해결했습니다.
<br/>
<br/>
> [FIX][FixPostWriter]몇몇 문제 수정 및 기능 변경

- src/main/java/com/ohgiraffers/mergyping/post/controller/PostController.java
- src/main/java/com/ohgiraffers/mergyping/post/model/dao/PostMapper.java
- src/main/java/com/ohgiraffers/mergyping/post/model/service/PostService.java
- src/main/resources/mappers/PostMapper.xml
- src/main/resources/templates/post/selectpost.html
댓글 수정 말고 삭제부터 먼저 하겠습니다..
<br/>
#163 
<br/>
<br/>
<br/>
> [FEATURE][ModifyComment]댓글 수정

- src/main/java/com/ohgiraffers/mergyping/post/controller/PostController.java
- src/main/java/com/ohgiraffers/mergyping/post/model/dto/SelectPostDTO.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dao/MyPageMapper.java
- src/main/resources/mappers/PostMapper.xml
- src/main/resources/static/css/post/newpost.css
- src/main/resources/templates/post/newpost.html
- src/main/resources/templates/post/selectpost.html
게시물 작성시 로그인한 작성자의 프로필 이미지가 들어갑니다
<br/>
#164
<br/>
<br/>
<br/>
> [FEATURE][UserProfileImageConnectDB]게시물 프로필 사진 연동

- src/main/java/com/ohgiraffers/mergyping/user/controller/AdminNoticeController.java
- src/main/java/com/ohgiraffers/mergyping/user/controller/ExceptionController.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dao/AdminNoticeMapper.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dto/AdminNoticeDTO.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dto/AdminNoticeDetailDTO.java
- src/main/java/com/ohgiraffers/mergyping/user/model/service/AdminNoticeService.java
- src/main/resources/mappers/AdminNoticeMapper.xml
- src/main/resources/static/css/admin/adminnotice.css
- src/main/resources/static/css/admin/adminnoticedetail.css
- src/main/resources/templates/user/admin/adminnotice.html
- src/main/resources/templates/user/admin/adminnoticedetail.html
모든 기능 정상적으로 작동합니다. 카테고리 수정이나 공지사항 생성할떄 카테고리도 정상적으로 작동합니다. 고칠 부분 있으면 말해주세요.
<br/>
<br/>
<br/>
<br/>
> [FIX][ADMINNOTICEFIX] 관리자 공지사항 카테고리 조회, 페이지네이션 수정

- src/main/java/com/ohgiraffers/mergyping/post/controller/PostController.java
- src/main/java/com/ohgiraffers/mergyping/post/model/dto/SelectPostDTO.java
- src/main/java/com/ohgiraffers/mergyping/user/controller/MyPageController.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dao/MyPageMapper.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dto/MyPageDTO.java
- src/main/java/com/ohgiraffers/mergyping/user/model/service/MyPageService.java
- src/main/resources/mappers/MyPageMapper.xml
- src/main/resources/mappers/PostMapper.xml
- src/main/resources/static/css/post/newpost.css
- src/main/resources/static/css/post/selectpost.css
- src/main/resources/templates/post/newpost.html
- src/main/resources/templates/post/selectpost.html
작성자 이름이랑 레벨 연동되게 햇습니당
<br/>
#176
<br/>
아직 게시물 작성시에는 int형으로 입력해야함..
<br/>
<br/>
> [FEATURE][PostWriterConnectLevel]게시글 작성자 레벨 연동

- src/main/java/com/ohgiraffers/mergyping/post/controller/PostController.java
- src/main/java/com/ohgiraffers/mergyping/post/model/dao/PostMapper.java
- src/main/java/com/ohgiraffers/mergyping/post/model/dto/SelectPostDTO.java
- src/main/java/com/ohgiraffers/mergyping/post/model/service/PostService.java
- src/main/java/com/ohgiraffers/mergyping/user/controller/MyPageController.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dao/MyPageMapper.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dto/MyPageDTO.java
- src/main/java/com/ohgiraffers/mergyping/user/model/service/MyPageService.java
- src/main/resources/mappers/MyPageMapper.xml
- src/main/resources/mappers/PostMapper.xml
- src/main/resources/static/css/post/newpost.css
- src/main/resources/static/css/post/selectpost.css
- src/main/resources/templates/post/newpost.html
- src/main/resources/templates/post/selectpost.html
이제 로그인 후 게시물 작성하기를 누르면 자신의 등급이랑 이름이 자동으로 작성자 정보칸에 들어가게했습니다
<br/>
#180
<br/>
<br/>
<br/>
> [FIX][PostWriterLoginUserNameAutoMatching]포스트 작성 시 로그인한 유저 이름 자동 매칭

- src/main/java/com/ohgiraffers/mergyping/user/controller/AdminNoticeController.java
- src/main/java/com/ohgiraffers/mergyping/user/controller/AdminReportController.java
- src/main/java/com/ohgiraffers/mergyping/user/controller/ExceptionController.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dao/AdminNoticeMapper.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dto/AdminNoticeDTO.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dto/AdminNoticeDetailDTO.java
- src/main/java/com/ohgiraffers/mergyping/user/model/service/AdminNoticeService.java
- src/main/resources/mappers/AdminNoticeMapper.xml
- src/main/resources/static/css/admin/adminnotice.css
- src/main/resources/static/css/admin/adminnoticedetail.css
- src/main/resources/static/css/admin/adminreport.css
- src/main/resources/templates/user/admin/adminnotice.html
- src/main/resources/templates/user/admin/adminnoticedetail.html
- src/main/resources/templates/user/admin/adminreport.html
관리자 신고관리 프론트입니다. 관리자페이지에서 신고관리 버튼 누르면 이등가능합니다.
<br/>
#183 
<br/>
<br/>
<br/>
> [FEATURE][FRONTADMINREPORTMANAGEMENT]관리자 신고관리 프론트

- src/main/java/com/ohgiraffers/mergyping/user/controller/AdminReportController.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dao/AdminReportMapper.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dto/AdminReportDTO.java
- src/main/java/com/ohgiraffers/mergyping/user/model/service/AdminReportService.java
- src/main/resources/mappers/AdminReportMapper.xml
- src/main/resources/static/css/admin/adminreport.css
- src/main/resources/templates/user/admin/adminreport.html
전체조회랑 페이지네이션 처리 했습니다. 7개 넘어가면 2페이지 버튼이 뜰탠데 이건 잘 모르겠네요
<br/>
#185 
<br/>
<br/>
<br/>
> [FEATURE][SELECTREPORTALL&PAGINATION]관리자 신고 전체조회 & 페이지네이션 처리

- src/main/java/com/ohgiraffers/mergyping/config/SecurityConfig.java
- src/main/java/com/ohgiraffers/mergyping/post/controller/PostController.java
- src/main/java/com/ohgiraffers/mergyping/post/model/dao/PostMapper.java
- src/main/java/com/ohgiraffers/mergyping/post/model/service/PostService.java
- src/main/resources/mappers/PostMapper.xml
- src/main/resources/static/css/post/selectpost.css
- src/main/resources/templates/post/edit.html
- src/main/resources/templates/post/post.html
- src/main/resources/templates/post/selectpost.html
게시물 수정, 게시물 삭제 프론트
<br/>
#42 
<br/>
도와주세요...
<br/>
<br/>
> [FEATURE][ModifyPost]게시물 수정 기능

- src/main/resources/static/css/admin/adminreport.css
- src/main/resources/templates/user/admin/adminreport.html
이제 신고관리에서 원하는 신고를 상세조회해서 볼 수 있습니다.
<br/>
#194
<br/>
<br/>
<br/>
> [FEATURE][DETAILSELECTREPORTMODAL]관리자 신고 상세조회 모달

- src/main/java/com/ohgiraffers/mergyping/comment/model/dto/CommentDTO.java
- src/main/java/com/ohgiraffers/mergyping/config/SecurityConfig.java
- src/main/java/com/ohgiraffers/mergyping/post/controller/PostController.java
- src/main/java/com/ohgiraffers/mergyping/post/model/dao/PostMapper.java
- src/main/java/com/ohgiraffers/mergyping/post/model/service/PostService.java
- src/main/resources/mappers/PostMapper.xml
- src/main/resources/static/css/post/selectpost.css
- src/main/resources/templates/post/edit.html
- src/main/resources/templates/post/post.html
- src/main/resources/templates/post/selectpost.html
댓글 좋아요 비동기로 db연결했습니다
클릭시 이미지가 바뀌고 좋아요라는 단어대신 현재 댓글의 누적 좋아요수가 표시됩니다
<br/>
#198
<br/>
<br/>
<br/>
> [FEATURE][CommentLikeFunction]댓글 좋아요 구현

- src/main/java/com/ohgiraffers/mergyping/user/controller/AdminReportController.java
- src/main/java/com/ohgiraffers/mergyping/user/model/dao/AdminReportMapper.java
- src/main/java/com/ohgiraffers/mergyping/user/model/service/AdminReportService.java
- src/main/resources/mappers/AdminReportMapper.xml
- src/main/resources/static/css/admin/adminreport.css
- src/main/resources/templates/user/admin/adminreport.html
모달창에서 신고 삭제를 누르면 알람이 뜨머 신고가 삭제됩니다.
<br/>
<br/>
<br/>
<br/>
> [FEATURE][DELETEREPORT]관리자 신고 삭제

- src/main/java/com/ohgiraffers/mergyping/post/controller/PostController.java
- src/main/resources/mappers/PostMapper.xml
- src/main/resources/templates/post/edit.html
- src/main/resources/templates/post/newpost.html
- src/main/resources/templates/post/selectpost.html
- src/test/java/com/ohgiraffers/mergyping/ApplicationTests.java
댓글 좋아요 및 게시글 좋아요 및 게시글 수정 삭제
<br/>
#43 
<br/>
<br/>
<br/>
> [FEATURE][COMMENTLIKE ] 댓글 좋아요 및 게시글 좋아요 및 게시글 수정 삭제

- src/main/resources/templates/post/selectpost.html
병합 문제 수정
<br/>
#238 
<br/>
<br/>
<br/>
> [FIX][FixMerge]병합 문제 수정

- src/main/java/com/ohgiraffers/mergyping/user/controller/CustomErrorController.java
- src/main/java/com/ohgiraffers/mergyping/user/controller/ExceptionController.java
- src/main/java/com/ohgiraffers/mergyping/user/controller/IntroController.java
- src/main/resources/static/css/error.css
에러페이지 작동문제 해결
<br/>
#208
<br/>
<br/>
<br/>
> [FIX][FixErrorPage]에러페이지 작동문제 해결

- src/main/java/com/ohgiraffers/mergyping/notice/controller/NoticeController.java
- src/main/java/com/ohgiraffers/mergyping/notice/model/service/NoticeService.java
- src/main/resources/static/css/notice/notice.css
- src/main/resources/templates/notice/notice.html
- src/main/resources/templates/user/admin/adminpostdetail.html
> [FIX][SEARCHNOTICE] 공지사항 검색

- src/main/resources/static/css/admin/admin.css
- src/main/resources/static/css/admin/adminpostdetail.css
- src/main/resources/templates/user/admin/admin.html
- src/main/resources/templates/user/admin/adminmanagement.html
- src/main/resources/templates/user/admin/adminnotice.html
- src/main/resources/templates/user/admin/adminnoticedetail.html
- src/main/resources/templates/user/admin/adminpost.html
- src/main/resources/templates/user/admin/adminpostdetail.html
- src/main/resources/templates/user/admin/adminreport.html
네브에서 마이페이지 누르면 관리자페이지로 가집니다.
<br/>
<br/>
<br/>
<br/>
> [FIX][ADMIN]관리자 페이지 수정

- src/main/resources/static/css/intro/intro-dark.css
- src/main/resources/static/css/intro/intro-light.css
- src/main/resources/static/css/mainpage/mainpage-darkmode.css
- src/main/resources/static/css/mainpage/mainpage-lightmode.css
- src/main/resources/templates/intro/intro.html
소개 페이지 라이트 모드 구현
<br/>
#220
<br/>
<br/>
<br/>
> [FEATURE][LightMode]인트로 라이트 모드 프론트 영역 구현

- src/main/resources/static/css/admin/adminnoticedetail-dark.css
- src/main/resources/static/css/admin/adminnoticedetail-light.css
- src/main/resources/static/css/intro/intro-dark.css
- src/main/resources/static/css/intro/intro-light.css
- src/main/resources/static/css/mainpage/mainpage-darkmode.css
- src/main/resources/static/css/mainpage/mainpage-lightmode.css
- src/main/resources/static/css/notice/notice-dark.css
- src/main/resources/static/css/notice/notice-light.css
- src/main/resources/templates/intro/intro.html
- src/main/resources/templates/notice/notice.html
- src/main/resources/templates/notice/selectnotice.html
- src/main/resources/templates/user/admin/adminnoticedetail.html
공지사항 라이트모드 구현
<br/>
#220
<br/>
<br/>
<br/>
> [FEATURE][LightMode]공지사항 라이트 모드 프론트 영역 구현
